// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

import { getDirectDatabaseUrl } from "./lib/database-url";

// Next.js usa .env.local en desarrollo; Prisma CLI también debe leerlo.
config();
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDirectDatabaseUrl(),
  },
});
